drop table if exists socio;
create table socio (id integer not null auto_increment, codice_fiscale varchar(17) not null, cognome varchar(50), nome varchar(50), primary key (id)) engine=InnoDB;
alter table socio add constraint UK_tox6grm7ohkl1mrr70yb2fyan unique (codice_fiscale);
drop table if exists socio;
create table socio (id integer not null auto_increment, codice_fiscale varchar(17) not null, cognome varchar(50), nome varchar(50), primary key (id)) engine=InnoDB;
alter table socio add constraint UK_tox6grm7ohkl1mrr70yb2fyan unique (codice_fiscale);
drop table if exists socio;
create table socio (id integer not null auto_increment, codice_fiscale varchar(17) not null, cognome varchar(50), nome varchar(50), primary key (id)) engine=InnoDB;
alter table socio add constraint UK_tox6grm7ohkl1mrr70yb2fyan unique (codice_fiscale);
drop table if exists socio;
create table socio (id integer not null auto_increment, codice_fiscale varchar(17) not null, cognome varchar(50), nome varchar(50), primary key (id)) engine=InnoDB;
alter table socio add constraint UK_tox6grm7ohkl1mrr70yb2fyan unique (codice_fiscale);
drop table if exists socio;
create table socio (id integer not null auto_increment, codice_fiscale varchar(17) not null, cognome varchar(50), nome varchar(50), primary key (id)) engine=InnoDB;
alter table socio add constraint UK_tox6grm7ohkl1mrr70yb2fyan unique (codice_fiscale);
drop table if exists socio;
create table socio (id integer not null auto_increment, codice_fiscale varchar(17) not null, cognome varchar(50), nome varchar(50), primary key (id)) engine=InnoDB;
alter table socio add constraint UK_tox6grm7ohkl1mrr70yb2fyan unique (codice_fiscale);
